<a href="https://colab.research.google.com/github/Satria1725/Data-Mining/blob/main/TugasPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Uang.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Budi' 10.0 6000.0]
 ['Handoko' 6.0 5000.0]
 ['Lucy' 7.0 5000.0]
 ['Nancy' 8.0 5000.0]
 ['Theo' 10.0 nan]
 ['Suci' 12.0 10000.0]
 ['Adriana' nan 7000.0]]


In [4]:
print(y)

['Laki-Laki' 'Laki-Laki' 'Perempuan' 'Perempuan' 'Laki-Laki' 'Perempuan'
 'Perempuan']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Budi' 10.0 6000.0]
 ['Handoko' 6.0 5000.0]
 ['Lucy' 7.0 5000.0]
 ['Nancy' 8.0 5000.0]
 ['Theo' 10.0 6333.333333333333]
 ['Suci' 12.0 10000.0]
 ['Adriana' 8.833333333333334 7000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 10.0 6000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 6.0 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 7.0 5000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 8.0 5000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 10.0 6333.333333333333]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 12.0 10000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 8.833333333333334 7000.0]]


In [9]:
print(y)

['Laki-Laki' 'Laki-Laki' 'Perempuan' 'Perempuan' 'Laki-Laki' 'Perempuan'
 'Perempuan']


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 0 1 1 0 1 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 6.0 5000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 10.0 6000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 10.0 6333.333333333333]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 8.0 5000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 12.0 10000.0]]


In [15]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 8.833333333333334 7000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 7.0 5000.0]]


In [16]:
print(y_train)

[0 0 0 1 1]


In [17]:
print(y_test)

[1 1]


In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [19]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.5 -0.5 -0.49999999999999994 -1.5689290811054721
  -0.7948923108829162]
 [0.0 1.0 0.0 0.0 -0.5 -0.5 -0.49999999999999994 0.3922322702763685
  -0.2529202807354731]
 [0.0 0.0 0.0 0.0 -0.5 -0.5 1.9999999999999998 0.3922322702763685
  -0.07226293735299225]
 [0.0 0.0 0.0 0.0 2.0 -0.5 -0.49999999999999994 -0.5883484054145518
  -0.7948923108829162]
 [0.0 0.0 0.0 0.0 -0.5 2.0 -0.49999999999999994 1.3728129459672889
  1.9149678398542993]]


In [20]:
print(x_test)

[[1.0 0.0 0.0 0.0 -0.5 -0.5 -0.49999999999999994 -0.17977312387666808
  0.28905174941197]
 [0.0 0.0 0.0 1.0 -0.5 -0.5 -0.49999999999999994 -1.078638743260012
  -0.7948923108829162]]
